# render.yaml - Defines all backend services for Render

services:
  # 1. The Managed Redis Database
  - name: video-redis
    type: redis
    plan: free
    ipAllowList: [] # FIX: Add an IP allow list. An empty list allows Render's internal services to connect.

  # 2. The Main API Server (Web Service)
  - name: video-api
    type: web
    plan: free
    rootDir: ./server
    env: docker
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: connectionString # FIX: Use 'connectionString' instead of 'internalUrl'.
      - fromGroup: backend-secrets

  # 3. The Background Workers
  - name: video-worker-360
    type: worker
    plan: free
    rootDir: ./server
    env: docker
    # FIX: Use 'dockerCommand' to specify a command for Docker-based workers.
    dockerCommand: node dist/workers/video.worker.js
    envVars:
      - key: QUEUE_NAME
        value: video_360p
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: connectionString # FIX: Use 'connectionString'.

  - name: video-worker-480
    type: worker
    plan: free
    rootDir: ./server
    env: docker
    dockerCommand: node dist/workers/video.worker.js
    envVars:
      - key: QUEUE_NAME
        value: video_480p
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: connectionString

  - name: video-worker-720
    type: worker
    plan: free
    rootDir: ./server
    env: docker
    dockerCommand: node dist/workers/video.worker.js
    envVars:
      - key: QUEUE_NAME
        value: video_720p
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: connectionString

  - name: video-worker-1080
    type: worker
    plan: free
    rootDir: ./server
    env: docker
    dockerCommand: node dist/workers/video.worker.js
    envVars:
      - key: QUEUE_NAME
        value: video_1080p
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: connectionString

  - name: cleanup-worker
    type: worker
    plan: free
    rootDir: ./server
    env: docker
    dockerCommand: node dist/workers/cleanup.worker.js
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: connectionString

# Environment variable group (no changes needed here, it was correct)
envVarGroups:
  - name: backend-secrets
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
