# render.yaml - Defines all backend services for Render

# The `services` key is the root of our blueprint definition.
services:
  # 1. The Managed Redis Database
  # This creates a free, managed Redis instance for our queues and caches.
  - name: video-redis
    type: redis
    plan: free

  # 2. The Main API Server (Web Service)
  # This is the public-facing service that handles HTTP and WebSocket connections.
  - name: video-api
    type: web
    plan: free
    rootDir: ./server # Tells Render to look for the Dockerfile in the /server directory.
    env: docker
    envVars: # Correct casing for environment variables.
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: internalUrl # Automatically gets the secure, internal Redis URL.
      - fromGroup: backend-secrets # Uses the shared secrets defined below.

  # 3. The Background Workers
  # Each worker is a separate service that runs in the background.

  - name: video-worker-360
    type: worker
    plan: free
    rootDir: ./server
    env: docker
    startCommand: node dist/workers/video.worker.js # Use the specific start command for video workers.
    envVars:
      - key: QUEUE_NAME
        value: video_360p # This worker only listens to the 360p queue.
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: internalUrl
      - fromGroup: backend-secrets

  - name: video-worker-480
    type: worker
    plan: free
    rootDir: ./server
    env: docker
    startCommand: node dist/workers/video.worker.js
    envVars:
      - key: QUEUE_NAME
        value: video_480p
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: internalUrl
      - fromGroup: backend-secrets

  - name: video-worker-720
    type: worker
    plan: free
    rootDir: ./server
    env: docker
    startCommand: node dist/workers/video.worker.js
    envVars:
      - key: QUEUE_NAME
        value: video_720p
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: internalUrl
      - fromGroup: backend-secrets

  - name: video-worker-1080
    type: worker
    plan: free
    rootDir: ./server
    env: docker
    startCommand: node dist/workers/video.worker.js
    envVars:
      - key: QUEUE_NAME
        value: video_1080p
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: internalUrl
      - fromGroup: backend-secrets

  - name: cleanup-worker
    type: worker
    plan: free
    rootDir: ./server
    env: docker
    startCommand: node dist/workers/cleanup.worker.js # The cleanup worker has its own dedicated start command.
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: internalUrl
      - fromGroup: backend-secrets

# This section defines a group of environment variables that can be shared across multiple services.
envVarGroups:
  - name: backend-secrets
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000 # Render will automatically map its internal port 3000 to the public port 443 (HTTPS).
      - key: CLOUDINARY_CLOUD_NAME
        sync: false # 'sync: false' marks this as a secret that you will enter manually in the Render dashboard.
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
